# see http://vagrantup.com
# Copyright (c) Niklaus Giger, <niklaus.giger@member.fsf.org>
# License: GPLv2
# Boxes are stored under ~/.vagrant.d/boxes/

Vagrant::Config.run do |config|
  # Setup the box
  config.vm.provision :puppet, :options => "--verbose --debug"
  config.vm.customize do |vm|
    vm.memory_size = 2048 # MB
  end
  config.vm.provision :puppet do |puppet|
    puppet.manifests_path = "manifests"
    puppet.manifest_file = "site.pp"
    puppet.module_path = "modules"
  end
  config.vm.define :elexisDev do |server|
    server.vm.network :hostonly, "10.11.12.43"
    server.vm.box     = "Elexis-Squeeze-i386"
    server.vm.host_name = "elexisDev32bit"
    server.vm.box_url = "/opt/fileserver/elexis/boxes/Elexis-Squeeze-i386.box"
    config.vm.boot_mode = :gui # :gui or :headless (default)
    server.vm.forward_port   22, 40022		# ssh
    server.vm.forward_port   80, 40080		# Apache
    server.vm.forward_port 3306, 43306		# MySQL
    server.vm.forward_port 4567, 44567		# Gollum (elexis-admin Wiki)
    server.vm.forward_port 8080, 48080		# Jenkins
  end
end
