#!/bin/bash

# Copyright (c) 2014 Niklaus Giger <niklaus.giger@member.fsf.org>

# Only for Debian jessie!
# Must be run as user root
# Fastest way to run it is "wget https://raw.github.com/ngiger/elexis-vagrant/master/shell/bootstrap_jessie && sudo bash -v bootstrap_jessie"

# Directory in which librarian-puppet should manage its modules directory
if [ -d /vagrant ] ; then PUPPET_DIR=/vagrant ; else PUPPET_DIR=/etc/puppet ; fi
if [ ! -d /vagrant ] ; then cp /vagrant/Puppetfile $PUPPET_DIR ; fi

cd $PUPPET_DIR

grep puppet /etc/.gitignore | grep puppet
if [ $? -ne 0  ] ; then
  echo puppet/ >> /etc/.gitignore
  echo hiera >> /etc/.gitignore
fi

# assure that we have the locale de_CH.utf8 installed or we will get errors
# like `encode': "\xC3" on US-ASCII (Encoding::InvalidByteSequenceError)
# when running vagrant provision
locale -a | grep de_CH
if [ $? -ne 0  ] ; then
  echo "Must generate locale de_CH.utf8"
  locale-gen de_CH.utf8
fi

sudo chmod 0600 /etc/ssh/*
version=`puppet --version | grep 3.7.2`
if [ $version = 3.7.2 ] ; then echo "Puppet 3.7.2 already installed"; exit;
else
  echo "Must install as version is $version"
fi

# ensure that we dont have an (older) version of puppet installed as gem
sudo gem uninstall --all --quiet hiera puppet
sudo apt-get update
sudo apt-get install -y --force-yes git puppet-common=3.7* hiera=1.3*  puppet=3.7*


