#!/usr/bin/env ruby
require 'yaml'
HieraMatchWithDefault = /hiera\((['"])([\w:]*)\1(,[^)]*)/
HieraMatchNoDefault   = /hiera\((['"])([\w:]*)\1/

def get_hiera_definitions_from_files(filename)
  definitions = {}
  inhalt = IO.readlines(filename)
  lineNr = 0
  inhalt.each{
    |line|        
  lineNr +=1
  if m = HieraMatchWithDefault.match(line)
    begin
      key = m[2]
      s = m[3]
      value = eval(s[s.index(',')+1..-1])
      definitions[key] = value
    rescue  => what
      puts "\nParsing #{filename} failed at line #{lineNr}"
      puts "Reason: "+ what.to_s
      puts "Line was: "+line
      puts "Match was #{m.inspect}"
      exit 2
    end
  elsif m = HieraMatchWithDefault.match(line)
      key = m[2]
      definitions[key] = '' if not definitions[key] and not definitions[key].eql?('')      
      puts "Error line #{lineNr} file: #{filename}"
      puts "Line was: "+line
      puts "All hiera definitions should have a default!"
      exit 2
  end
  } 
  definitions
end

defs = Hash.new
(Dir.glob('manifests/**/*.pp') + Dir.glob('modules/**/*.pp')).each{ |f| defs.merge!(get_hiera_definitions_from_files(f))}

outName = 'hiera/common.yaml'
ausgabe = File.open(outName, 'w+')
ausgabe.puts <<EOF
# File #{outName} generated by #{__FILE__}
# created at #{Time.now}
# Here you find all hiera definitions used in manifests and modules
EOF

ausgabe.puts defs.to_yaml