#!/bin/bash -v
# To be use on a vagrant machine
# prepare environment for librarian-puppet
gem list --local librarian-puppet | grep librarian-puppet
if [ $? -ne 0 ] ; then
  gem install --no-ri --no-rdoc librarian-puppet
fi
time librarian-puppet install # --verbose
