# Vorgabewerte für das Elexis-Cockpit
---
# If you have MySQL backups named like
# /home/backup/mysql/mysql_backup_20130310-230501.sql.bz2
# set the next two lines like
"::db::backup::dir": /home/backup
"::db::backup::name": mysql
elexis:mysql:included: true
"::db::backup::mysql::script":      /usr/local/sbin/mysqlbackup.sh
"::db::backup::postgresql::script": /usr/local/bin/pg_dump_elexis.rb
# Name of first DB-server
"::db::server": localhost
# Name of second DB-server
"::db::backup": tr-ng
# Tell who is the backup DB server (or false) if there is no online backup
"::db::server::backup_server_is": tr-ng
"::db::port": 3306
"::db::user": elexis
"::db::main": elexis
# Scripts to format and encrypt external HD disk
"::hd::external::format_and_encrypt": /opt/src/elexis-vagrant/modules/elexis/files/backup_encrypted.rb.erb

elexis:mysql:included: true
