source "http://rubygems.org"

gem "sinatra"
gem "shotgun"
gem "sqlite3" 
gem "datamapper" 
gem "dm-sqlite-adapter"
gem "builder"
gem "RedCloth"

gem "rack-test"
gem "rspec"
gem "sys-filesystem"
gem "hiera"
gem "erubis"
gem "actionpack"
gem 'nokogiri'
gem 'action_view'
gem 'activerecord-import'