source "http://rubygems.org"

gem "sinatra", ">=1.3.5"
gem "shotgun"
gem "sqlite3" 
gem "datamapper" 
gem "dm-sqlite-adapter"
gem "builder"
gem "RedCloth"

# gem "rack-test"
# gem "rspec"
gem "sys-filesystem"
gem "hiera"
# gem "erubis"
gem "actionpack" , ">=4.0.0.beta1" 
gem 'nokogiri'
gem 'activesupport'
gem 'i18n_rails_helpers'
gem 'haml'